export const AUTHENTICATION_FLOW = 'AUTHENTICATION_FLOW';
export const LOGOUT_FLOW = 'LOGOUT_FLOW';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const LOGOUT = 'LOGOUT';

export const SIGN_UP_FLOW = 'SIGN_UP_FLOW';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const VERIFYING_TOKEN_FLOW = 'VERIFYING_TOKEN_FLOW';
export const VERIFYING_TOKEN_PENDING = 'VERIFYING_TOKEN_PENDING';
export const TOKEN_INVALIDATE = 'TOKEN_INVALIDATE';
export const TOKEN_VALID = 'TOKEN_VALID';

export const REDIRECT_AFTER_LOGIN = 'REDIRECT_AFTER_LOGIN';