export const AUTHENTICATION_FLOW = 'AUTHENTICATION_FLOW';
export const LOGOUT_FLOW = 'LOGOUT_FLOW';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const LOGOUT = 'LOGOUT';

export const SIGN_UP_FLOW = 'SIGN_UP_FLOW';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const VERIFYING_TOKEN_FLOW = 'VERIFYING_TOKEN_FLOW';
export const VERIFYING_TOKEN_PENDING = 'VERIFYING_TOKEN_PENDING';
export const TOKEN_INVALIDATE = 'TOKEN_INVALIDATE';
export const TOKEN_VALID = 'TOKEN_VALID';

export const GET_PRODUCTS_FLOW = 'GET_PRODUCTS_FLOW';
export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const BEGIN_CHECKOUT_FLOW = 'BEGIN_CHECKOUT_FLOW';
export const CHECKOUT_PENDING = 'CHECKOUT_PENDING';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';

export const BEGIN_ORDERS_FLOW = 'BEGIN_ORDERS_FLOW';
export const RETRIEVE_ORDERS = 'RETRIEVE_ORDERS';
export const RETRIEVE_ORDERS_PENDING = 'RETRIEVE_ORDERS_PENDING';
export const RETRIEVE_ORDERS_SUCCESS = 'RETRIEVE_ORDERS_SUCCESS';
export const RETRIEVE_ORDERS_FAILURE = 'RETRIEVE_ORDERS_FAILURE';
export const REDIRECT_AFTER_LOGIN = 'REDIRECT_AFTER_LOGIN';
